pipeline {
    agent any

    environment {
        TF_DIR = "vpc" // Update if the correct folder is different
    }

    stages {
        stage('Checkout Code') {
            steps {
                git branch: 'main', url: 'https://github.com/RahulVarne/terraform.git'
            }
        }

        stage('Verify Terraform Files') {
            steps {
                sh '''
                echo "Checking Terraform directory..."
                ls -l $TF_DIR
                '''
            }
        }

        stage('Terraform Init') {
            steps {
                dir(TF_DIR) {
                    withAWS(credentials: 'aws-credentials', region: 'us-east-1') {
                        sh 'terraform init'
                    }
                }
            }
        }

        stage('Terraform Plan') {
            steps {
                dir(TF_DIR) {
                    withAWS(credentials: 'aws-credentials', region: 'us-east-1') {
                        sh 'terraform plan -out=tfplan'
                    }
                }
            }
        }

        stage('Terraform Apply') {
            steps {
                dir(TF_DIR) {
                    withAWS(credentials: 'aws-credentials', region: 'us-east-1') {
                        sh 'terraform apply -auto-approve tfplan'
                    }
                }
            }
        }

        stage('Terraform Destroy') {
            steps {
                dir(TF_DIR) {
                    withAWS(credentials: 'aws-credentials', region: 'us-east-1') {
                        sh 'terraform destroy -auto-approve'
                    }
                }
            }
        }
    }
}
